### PR TITLE
Change logo order [#210]

### PR DESCRIPTION
**Pull request by sandrahoang686**
Closing https://github.com/NASA-IMPACT/veda-config-ghg/issues/210

### CODE REVIEW

**Comment by j08lue** [comment]
What is the status on this one?

**Comment by slesaad** [comment]
For the last bullet in #210 - https://github.com/NASA-IMPACT/veda-config-ghg/pull/223

**Review by j08lue — APPROVED** [review]
I did a visual side-by-side comparison of the logo orders in all places mentioned in #210 and all seems to be complete. 💯

**Comment by j08lue** [comment]
I'll take the liberty to merge this. We can always go back and edit again, if needed, but this looks complete to me.

**Pull request merged**
