### PR TITLE
Data catalog content

### PR DESCRIPTION
**Pull request by siddharth0248**
## Changes

- [ ] ...
- [x] [Search](https://github.com/search?q=repo%3ANASA-IMPACT%2Fveda-config-ghg%20cog_transformation_scripts&type=code) for `cog_transformation_scripts` and replace with `cog_transformation`
- [x] Resolve merge conflicts
- [ ] Add the projection `Equirectangular` to all configured datasets, as described in the [docs](https://github.com/NASA-IMPACT/veda-ui/blob/71be3222ea27c8676c5ddf9c2cfc676c4f6b06dc/docs/content/frontmatter/layer.md#projection) - closes https://github.com/NASA-IMPACT/veda-config-ghg/issues/44

### CODE REVIEW

**Comment by j08lue** [comment]
I see the merge conflicts are due to changes like this one, @siddharth0248:

```
<<<<<<< HEAD
      datasetId: odiac-ffco2-monthgrid-v2022-ghgc
=======
      datasetId: odiac-ffco2-monthgrid-v2022
>>>>>>> develop
```


```
<<<<<<< HEAD
    stacCol: nasa-jpl-plumes-emissions-updated
    name: CH4 point source plume complexes
=======
    stacCol: emit-ch4plume-v1
    name: CH4 plumes emissions
>>>>>>> develop
```

I don't know which ones we should keep - will you resolve the conflicts? Or tell me whether `develop` or your branch is correct, if that is consistent.

**Comment by j08lue** [comment]
I tried changing the default map projection for the CASA GFED dataset in this commit https://github.com/NASA-IMPACT/veda-config-ghg/pull/55/commits/851f566f6443aa56bad2071e5612e41ca6516ef4

It worked but the setting does not seem to get applied when the Exploration view initially loads, only when you start clicking on layers.

I raised that here and will wait with more projection changes until that gets resolved / answered.

**Comment by j08lue** [comment]
Hey @siddharth0248, I created a PR against this branch here that should fix the merge conflicts (hopefully in the right way). Please review and merge asap, before committing much more to your branch here, to avoid new merge conflicts.

https://github.com/NASA-IMPACT/veda-config-ghg/pull/64

**Comment by slesaad** [comment]
Looks good for now, but should we update all the links to go to the ghgc-docs website rather than raw github links?

**Review by slesaad — APPROVED** [review]

**Pull request merged**
